/// Meshtastic protobuf types.
///
/// Generated by `prost-build` from the official
/// [meshtastic/protobufs](https://github.com/meshtastic/protobufs) submodule.
///
/// The full Meshtastic proto corpus is available under [`generated::meshtastic`].
/// Commonly used types are re-exported at this level for convenience.

pub mod generated;

// ── Re-exports ───────────────────────────────────────────────────────────────

// Core mesh types.
pub use generated::meshtastic::Data;
pub use generated::meshtastic::User;
pub use generated::meshtastic::Position;
pub use generated::meshtastic::MeshPacket;
pub use generated::meshtastic::NodeInfo;
pub use generated::meshtastic::MyNodeInfo;
pub use generated::meshtastic::FromRadio;
pub use generated::meshtastic::ToRadio;
pub use generated::meshtastic::ServiceEnvelope;
pub use generated::meshtastic::PortNum;

// Oneof sub-modules (needed for pattern matching).
pub use generated::meshtastic::mesh_packet;
pub use generated::meshtastic::from_radio;
pub use generated::meshtastic::to_radio;

// ── Helper impls ─────────────────────────────────────────────────────────────

impl User {
    /// Encode to bytes suitable for wrapping in a [`Data`] payload.
    pub fn encode_to_data(&self) -> Data {
        use prost::Message;
        Data {
            portnum: PortNum::NodeinfoApp as i32,
            payload: self.encode_to_vec(),
            ..Default::default()
        }
    }
}

impl Data {
    /// Decode a `User` from a `NODEINFO_APP` payload.
    pub fn decode_user(&self) -> Result<User, prost::DecodeError> {
        use prost::Message;
        User::decode(self.payload.as_slice())
    }

    /// Interpret `TEXT_MESSAGE_APP` payload as a UTF-8 string.
    pub fn text(&self) -> Option<&str> {
        if self.portnum == PortNum::TextMessageApp as i32 {
            std::str::from_utf8(&self.payload).ok()
        } else {
            None
        }
    }
}
